[package]
name = "message_server"
version = "0.1.0"
authors = ["Teemu Erkkola <teemu.erkkola@gofore.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
message-io = "0.12"
chatrs = { path = ".." }
