[package]
name = "web_client"
version = "0.1.0"
authors = ["Teemu Erkkola <teemu.erkkola@gofore.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.67"
chatrs = { path = ".." }
